name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: .\run.ps1
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            tmp/
